---
title: "RF2"
author: "Melanie Hay"
date: "2022-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, read in test-train split 2 with no alphadiversity}

test2.na.df <- read.csv("df/rf/test2.na.df.csv")
train2.na.df <- read.csv("df/rf/train2.na.df.csv")

```

```{r, groupKFold (from caret) on training set to split farms into diffrent test sets}
k <- length(unique(train2.df$Farm_uni_ID))
k
#head(folds[2])
folds2 <- groupKFold(train2.df$Farm_uni_ID, k = 10) 
```


# Turn categorical to dummy
```{r}
train2.df <- as.data.frame(unclass(train2.df), stringsAsFactors = TRUE)
dummies = dummyVars(PA2 ~ ., data = train2.df) # convert categorical variables to dummies
dummies_train2 <- data.frame(predict (dummies, newdata = train2.df))
dummies_train2$PA2 <- train2.df$PA2
```

# Preprocess train and test separately

```{r}
training.sep2 <- dummies_train2
#testing.sep2 <- test2.df


# Non zero variance
nzv(training.sep2)
nzv(testing.sep2)

# Highly correlated
training.sep2.cor <- training.sep2[61:90]
calculateCor2 <- cor(training.sep2.cor[1:29])
summary(calculateCor2[upper.tri(calculateCor2)], cutoff = 0.9)

# 
highlyCor2 <- findCorrelation(calculateCor2) #pick highly correlated variables
colnames(training.sep2.cor)[highlyCor2]

highlyCorDescr2 <- findCorrelation(calculateCor2, cutoff = .9)
highlyCorDescr2
```

```{r}
set.seed(1234)

seeds2 = vector(mode="list", length=101)
for (i in 1:100) seeds2[[i]] = sample.int(1000,486)
seeds2[[101]] = sample.int(1000,1)

```


```{r}
trControl2 <- trainControl(method = "repeatedcv",
    number=10,                   
    repeats=7,
    p = 0.85,
    sampling = "down",
    seeds=seeds2,
    index=folds2,
    search = "grid",
    savePredictions = "all",
    returnResamp = "all",
    classProbs=TRUE)
```

```{r}
train2.model.df <- train2.df[2:29]
set.seed(1234)
# Run the model
rf_train2 <- train(PA2 ~ .,
    method="rf",
    data = train2.model.df,
    importance=TRUE,
    na.action = na.omit,
    metric = "Accuracy",
    trControl = trControl2)

# Print the results
print(rf_train2)
rf_train2$results
```



```{r, Search best mtry}
set.seed(1234)
tuneGrid2 <- expand.grid(.mtry = c(15: 150))
rf_mtry <- train(PA2 ~.,
    data = train2.model.df,
    method = "rf",
    metric = "Accuracy",
    tuneGrid = tuneGrid2,
    trControl = trControl2,
    nodesize = 1,
    na.action = na.omit,
    ntree = 300)
print(rf_mtry)
```


```{r}
best_mtry <- rf_mtry$bestTune$mtry 
best_mtry

```

```{r, Step 3) Search the best maxnodes}

store_maxnode <- list()
tuneGrid2 <- expand.grid(.mtry = best_mtry) ### warning- I've hard-coded a m-try to debug
for (maxnodes in c(5: 10)) {
    rf_maxnode <- train(PA2 ~.,
        data = train2.model.df,
        method = "rf",
        metric = "Accuracy",
        tuneGrid = tuneGrid2,
        trControl = trControl2,
        importance = TRUE,
        nodesize = 2,
        na.action = na.omit,
        maxnodes = maxnodes,
        ntree = 300)
    current_iteration <- toString(maxnodes)
    store_maxnode[[current_iteration]] <- rf_maxnode
}
results_mtry <- resamples(store_maxnode)
summary(results_mtry)

```

```{r, Step 4) Search the best ntrees}

store_maxtrees <- list()
for (ntree in c(250, 300, 350, 400, 450, 500, 550, 600, 800, 1000, 2000)) {
    rf_maxtrees <- train(PA2 ~.,
        data = train2.model.df,
        method = "rf",
        metric = "Accuracy",
        tuneGrid = tuneGrid2,
        trControl = trControl2,
        importance = TRUE,
        maxnodes = 5,
        nodesize = 1,
        na.action = na.omit,
        ntree = ntree)
    key <- toString(ntree)
    store_maxtrees[[key]] <- rf_maxtrees
}
results_tree <- resamples(store_maxtrees)
summary(results_tree)

```



```{r}
fit_rf_2 <- train(PA2 ~.,
    train2.model.df,
    method = "rf",
    metric = "Accuracy",
    tuneGrid = tuneGrid2,
    trControl = trControl2,
    importance = TRUE,
    maxnodes = 19,
    nodesize = 1,
    ntree = 400,
    na.action = na.omit)

```

```{r, fig.height=4, fig.width=12}
varImp(fit_rf_2)
gbmImp2 <- varImp(fit_rf_2)
plot(gbmImp2, top = 20)
summary(fit_rf_2)

rf2_varimp <- as.data.frame(gbmImp2$importance)
```



```{r, fig.height=4, fig.width=12}
gmbImp2.df <- as.data.frame(gbmImp2$importance)
#write.csv(gmbImp2.df, "df/figure_edit/gbmImp2_edit.csv")

importance2.df <- read.csv("df/figure_edit/gbmImp2_edit.csv", row.names = 1)
gbmImp2$importance <- as.data.frame(importance2.df)

png("images/RF2Imp.png", width=12, height=4, units="in", res =300)
RF2Imp <- plot(gbmImp2, top = 20)
RF2Imp
dev.off()


```


```{r}
test2.model.df <- test2.df[2:29] 
prediction2 <-predict(fit_rf_2, test2.model.df)

prediction2
test2.model.df$PA2 <- as.factor(test2.model.df$PA2)

identical(levels(prediction2),levels(test2.model.df$PA2))
confusionMatrix(prediction2, test2.model.df$PA2)

```


