---
title: "Networks"
author: "Melanie Hay"
date: "31/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(phyloseq)
library(NetCoMi)
library(qgraph)
library(svglite)
library(igraph)
```


# Getting the data

You can also embed plots, for example:

```{r pressure, echo=FALSE}
#outliers_count.381 <- readRDS("path")
outliers_count.381

outliers_count.380noK <- subset_taxa(outliers_count.381, Genus!= "Kingdom_Bacteria")
outliers_count.379noK <- subset_taxa(outliers_count.380noK, Genus!= "Kingdom_")
outliers_count.379noK

```
# Splitting the data to use with our enterotypes

The first thing we want to do is add the Enterotype of each sample as a column. 

```{r}
sample_data(outliers_count.379noK)$Enterotype <- pam_all_18_datasets.df$PA2
```

```{r}
PA1.ps.N <- subset_samples(outliers_count.379noK, Enterotype == "PA2.1")
PA1.ps.N <- prune_taxa(taxa_sums(PA1.ps.N) > 0, PA1.ps.N) 
PA1.ps.N

PA2.ps.N <- subset_samples(outliers_count.379noK, Enterotype == "PA2.2")
PA2.ps.N <- prune_taxa(taxa_sums(PA2.ps.N) > 0, PA2.ps.N) 
PA2.ps.N

PA3.ps.N <- subset_samples(outliers_count.379noK, Enterotype == "PA2.3")
PA3.ps.N <- prune_taxa(taxa_sums(PA3.ps.N) > 0, PA3.ps.N) 
PA3.ps.N

#saveRDS(PA1.ps.N, "PA1.ps.N.rds")
#saveRDS(PA2.ps.N, "PA2.ps.N.rds")
#saveRDS(PA3.ps.N, "PA3.ps.N.rds")
```

```{r}

# Get phyla names from the taxonomic table created before
taxtab379 <- as.data.frame(tax_table(outliers_count.379noK))

phyla <- as.factor(gsub("p__", "", taxtab379[, "Phylum"]))
names(phyla) <- row.names(taxtab379)
table(phyla)

phyla.df <- as.data.frame(phyla)
phyla.df$ASV <- row.names(phyla.df)

```

# Create figures
```{r}
#nb.cols <- 24
#mycolors22 <- colorRampPalette(brewer.pal(8, "Paired"))(nb.cols)

phyla_palette = c("#AD1457", "#FF9800", "#F44336", "grey", "#009688", "grey", "#f9dc5c", "pink", "grey","#339cff","#448AFF","#307cff", "#3f51b5", "#303f9f", "grey", "grey", "#6d8ea0", "#4cb04f", "#8BC34A", "#FFC107", "brown", "wheat","grey", "#763fa3") 
```

# ENTEROTYPE 1 
# Network construction
```{r}
# Network construction and analysis
# NB NB NB This needs to be run on a ps object with COUNT data, not RA
net_single_PA1.N <- netConstruct(PA1.ps.N, 
                            measure = "sparcc",
                            zeroMethod = "multRepl",
                            filtTax = c("numbSamp","relFreq"),
                            filtTaxPar = list(numbSamp = 29, relFreq =0.00015),
                            sparsMethod = "threshold", 
                            thresh = 0.3, 
                            verbose = 3)

saveRDS(net_single_PA1.N, "PA1.net")
```

# Network analysis
```{r, fig.height= 7, fig.width=15}

props_singlePA1.N <- netAnalyze(net_single_PA1.N, clustMethod = "cluster_fast_greedy")

```

# Plot our network
```{r, fig.height= 7, fig.width=15}
library(svglite)

svg("PA1_Net_10prev_0.00015RA.svg", width = 18, height = 10)

base::plot(props_singlePA1.N, 
           layout="spring",
           shortenLabels = "intelligent",
     nodeColor = "feature", 
     featVecCol = phyla, 
     colorVec =  phyla_palette,
     nodeSize = "clr",
     repulsion = 0.92,
     rmSingles = TRUE,
     labelScale = FALSE,
     labelFont = 1,
     cexLabels = 0,
     cexHubLabels = 1,
     nodeSizeSpread = 3,
     cexNodes = 2,
     title1 = "PA1 Network on genus level with SparCC correlations (0.3) (10% prev, 0.00015 RA)", 
     showTitle = TRUE,
     cexTitle = 1.5)

legend(0.7, 1.1, inset = 0.25, cex = 1.5, title = "estimated correlation:",
       legend = c("+","-"), lty = 1, lwd = 3, col = c("#009900","red"),
       bty = "n", horiz = TRUE)


#legend("bottomleft", cex = 1, pt.cex = 1.5, title = "Phylum:", 
       #legend=levels(phyla), col = phyla_palette, bty = "n", pch = 16, horiz = FALSE, xpd = TRUE) 

dev.off()
#ggsave("PA1_Net_10prev_0.0015RA.svg", width = 40, height = 20)
```

# List the network hubs

```{r}
props_singlePA1.N$hubs

```
# ENTEROTYPE 2

```{r}
# Network construction and analysis
# NB NB NB This needs to be run on a ps objkect with COUNT data, not RA
net_single_PA2.N <- netConstruct(PA2.ps.N, 
                            measure = "sparcc",
                            zeroMethod = "multRepl",
                            filtTax = c("numbSamp","relFreq"),
                            filtTaxPar = list(numbSamp = 14, relFreq =0.00015),
                            sparsMethod = "threshold", 
                            thresh = 0.3, 
                            verbose = 3)

saveRDS(net_single_PA2.N, "PA2.net")
```


```{r}
props_singlePA2.N <- netAnalyze(net_single_PA2.N, clustMethod = "cluster_fast_greedy")
```

```{r, fig.height= 7, fig.width=15}
svg("PA2_Net_10prev_0.00015RA.svg", width = 18, height = 10)

base::plot(props_singlePA2.N, 
           layout="spring",
           shortenLabels = "intelligent",
     nodeColor = "feature", 
     featVecCol = phyla, 
     colorVec =  phyla_palette,
     nodeSize = "clr",
     repulsion = 0.92,
     rmSingles = TRUE,
     labelScale = FALSE,
     labelFont = 1,
     cexLabels = 0,
     cexHubLabels = 1,
     nodeSizeSpread = 3,
     cexNodes = 2,
     title1 = "PA2 Network on genus level with SparCC correlations (0.3) (10% prev, 0.00015 RA)", 
     showTitle = TRUE,
     cexTitle = 1.5)

legend(0.7, 1.1, inset = 0.25, cex = 1.5, title = "estimated correlation:",
       legend = c("+","-"), lty = 1, lwd = 3, col = c("#009900","red"),
       bty = "n", horiz = TRUE)


#legend("bottomleft", cex = 1, pt.cex = 1.5, title = "Phylum:", 
 #      legend=levels(phyla), col = phyla_palette, bty = "n", pch = 16, horiz = FALSE, xpd = TRUE) 

dev.off()
```

```{r}
props_singlePA2.N$hubs

```

# ENTEROTYPE 3

```{r}
# Network construction and analysis
# NB NB NB This needs to be run on a ps object with COUNT data, not RA
net_single_PA3.N <- netConstruct(PA3.ps.N, 
                            measure = "sparcc",
                            zeroMethod = "multRepl",
                            filtTax = c("numbSamp","relFreq"),
                            filtTaxPar = list(numbSamp = 7, relFreq =0.00015),
                            sparsMethod = "threshold", 
                            thresh = 0.3, 
                            verbose = 3)

```


```{r, fig.height= 7, fig.width=15}
props_singlePA3.N <- netAnalyze(net_single_PA3.N,
                                clustMethod = "cluster_fast_greedy")
```

```{r, fig.height= 7, fig.width=15}
svg("PA3_Net_10prev_0.00015RA_with_labels.svg", width = 18, height = 10)

clust1 <- props_singlePA3.N$clustering$clust1

base::plot(props_singlePA3.N,
           layout = "spring",
           shortenLabels = "intelligent",
           edgeFilter = "threshold",
           edgeFilterPar = 0.4,
     nodeColor = "feature",
     #nodeTransp = 10,
     featVecCol = phyla, 
     colorVec =  phyla_palette,
     nodeSize = "clr",
     repulsion = 0.92,
     rmSingles = TRUE,
     labelScale = FALSE,
     labelFont = 1,
     cexLabels = 0.5,
     cexHubLabels = 1,
     nodeSizeSpread = 3,
     cexNodes = 2,
     title1 = "PA3 Network on genus level with SparCC correlations (0.4) (10% prev, 0.00015 RA)", 
     showTitle = TRUE,
     cexTitle = 1.5)

legend(0.7, 1.1, inset = 0.25, cex = 1.5, title = "estimated correlation:",
       legend = c("+","-"), lty = 1, lwd = 3, col = c("#009900","red"),
       bty = "n", horiz = TRUE)


#legend("bottomleft", cex = 1, pt.cex = 1.5, title = "Phylum:", 
       #legend=levels(phyla), col = phyla_palette, bty = "n", pch = 16, horiz = FALSE, xpd = TRUE) 

dev.off()
```
